import type { Metadata } from "next";
import { Poppins, Cinzel } from "next/font/google";
import "./globals.css";
import { ViewTransitions } from "next-view-transitions";
import ClientProvider from "@/components/layout/client-provider";
import { AppContextProvider } from "@/components/layout/context-provider";
import QueryProvider from "@/components/layout/query-provider";
import ToastProvider from "@/components/layout/toast-provider";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import { configs } from "@/lib/constants";

const fDefault = Poppins({
  variable: "--font-default",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

const fPrimary = Cinzel({
  variable: "--font-primary",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

// export const metadata: Metadata = {
//   title: "Create Core",
//   description: "Generated by Jee",
// };

export async function generateMetadata(): Promise<Metadata> {
  const global = await fetch(
    `${configs.API_BASE}/global?populate[favicon]=true&populate[defaultSeo][populate]=shareImage`,
    {
      headers: {
        "Content-Type": "application/json",
        apiKey: configs.API_KEY,
        Authorization: `Bearer ${configs.TOKEN}`,
      },
      next: { revalidate: 10 },
    },
  )
    .then((res) => res.json())
    .catch(() => null);

  if (!global?.data) {
    return {
      icons: {
        icon: "/images/icon/logo1.svg",
        shortcut: "/images/icon/logo1.svg",
        apple: "/images/icon/logo1.svg",
      },
    };
  }
  const baseImage = configs.BASE_IMAGE || "";
  const faviconUrl = global.data.favicon?.url ? baseImage + global.data.favicon.url : "/images/icon/logo1.svg";
  const ogImageUrl = baseImage + global.data.defaultSeo?.shareImage?.url;

  return {
    title: {
      default: global.data.defaultSeo?.metaTitle || global.data.siteName || "SMP Islam Nurtech",
      template: `%s | ${global.data.siteName || "SMP Islam Nurtech"}`,
    },

    description:
      global.data.defaultSeo?.metaDescription || global.data.siteDescription,

    applicationName: global.data.siteName,

    icons: {
      icon: faviconUrl || "/images/icon/logo1.svg",
      shortcut: faviconUrl || "/images/icon/logo1.svg",
      apple: faviconUrl || "/images/icon/logo1.svg",
    },

    openGraph: {
      siteName: global.data.siteName,
      title: global.data.defaultSeo.metaTitle,
      description: global.data.defaultSeo.metaDescription,
      images: ogImageUrl
        ? [
            {
              url: ogImageUrl,
              width: 1200,
              height: 630,
              alt: global.data.siteName,
            },
          ]
        : [],
    },
  };
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="en">
        <body
          className={`${fDefault.variable} ${fPrimary.variable} antialiased`}
        >
          <AppContextProvider>
            <ToastProvider />
            <QueryProvider>
              <ClientProvider>
                <Navbar />
                {children}
                <Footer />
              </ClientProvider>
            </QueryProvider>
          </AppContextProvider>
        </body>
      </html>
    </ViewTransitions>
  );
}
